name: primeiro-workflow #nome tecnico
run-name: Meu primeiro workflow #nome mais humanizado

on: 
    push:
        branches:
            - main

jobs:
    mac: 
        runs-on: macos-latest
        steps:
            - name: Rodar um hello no mac
              run: echo "Rodou no mac"



