name: primeiro-workflow #nome tecnico
run-name: Meu primeiro workflow #nome mais humanizado

on: [push] # qualquer branch quando rodar, vai rodar nos pipelines (CD -main)

#event apenas na branch main
on: 
    push:
        branches:
            - main

jobs:
    mac: 
        runs-on: macos-latest
        steps:
            - name: Rodar um hello no mac
              run: echo "Rodou no mac"



